import { Roboto as FontSans } from "next/font/google";
import "./global.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";

export const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn("flex flex-col min-h-screen w-full", fontSans.className)}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
